### ISSUE TITLE
pgjdbc source(version 42.2.8) with jre7, produces two jar packages

### ISSUE THREAD

**Issue by LittleWuCoding** [pgjdbc/pgjdbc-jre7#8]
when I compile the pgjdbc source(version 42.2.8) with jre7, it produces two jar packages which are
```
original-postgresql-42.2.8.jre7.jar
postgresql-42.2.8.jre7.jar
```
But when I use old version of pgjdbc (42.2.1),it just it produces one package:
```
postgresql-42.2.1.jre7.jar
```
I have had using postgresql-xxxxx.jre7.jar for a long time(jre7 version), but now when using 42.2.8,it produces two packages, which package should I take if I want the pgjdbc just works as before?

Further more, I want to know what the different between  original-postgresql-42.2.8.jre7.jar and postgresql-42.2.8.jre7.jar ?

I am new to java and mvn . I am sorry if I ask a stupid question.

**Comment by davecramer** [comment]
the original jar is before we add all the dependencies into it.

You want the postgresql-42.2.8.jre7.jar

Quick question: we are contemplating dropping support for java 7. Is there a reason you are not using java 8 ?

**Comment by LittleWuCoding** [comment]
Thanks for your reply. 
The reason why I still using jre7 and jre6 is that my customers still using old java version.
I just want to keep compatible.
